### ISSUE TITLE
Changin the Stream Manager  SSO button to NEW TAB

### ISSUE THREAD

**Issue by shenkarcollage** [mattan-d/moodle-local_stream#5]
In the 
Recording list in Moodle
There is the button of connecting to sso manager
Would be great if it can be a click which open a new window \Tab (better)  so the teachers can still stay on Moodle page

Thank you

**Comment by mattan-d** [comment]
Fix SSO Manager button to open in a new tab (#5)

Implemented functionality to ensure the SSO Manager button in the Recording list opens in a new tab. This allows teachers to access the SSO Manager without leaving the Moodle page, enhancing usability.
