### ISSUE TITLE
when trying to change name in "my records" we get an error

### ISSUE THREAD

**Issue by shenkarcollage** [mattan-d/moodle-local_stream#6]
Hey
in "my records list" page
when clicking the pencil and changing the name and clicking enter
there is an error
see image
![image](https://github.com/user-attachments/assets/4be06599-5c22-494e-9aaf-bddf23491ec4)

thank you

**Comment by mattan-d** [comment]
Hello @shenkarcollage,

The issue with changing names in the "My Records List" page has been resolved. Users can now click the pencil icon, edit the name, and press enter without encountering error #6.
